{% set name = "skrub" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f40ec8dfa9ee9ad5a75397d0eb7c87fe110def9d5ca649d64c600b2e357bce1

build:
  skip: true  # [py<39]  
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools >=64
    - setuptools-scm >=8
    - pip
    - wheel
  run:
    - python
    - numpy >=1.23.5
    - packaging >=23.1
    - pandas >=1.5.3
    - scikit-learn >=1.2.1
    - scipy >=1.9.3
    - jinja2 >=3.1.2
    - matplotlib-base >=3.4.3
    - requests >=2.25.0

test:
  imports:
    - skrub
  requires:
    - pip
    - pytest
    - numpydoc
    - pytest-cov
    - pytest-xdist
  source_files:
    - skrub/tests
    - skrub/conftest.py
    - pyproject.toml 
  commands:
    - pip check
    - pytest skrub/tests

about:

  home: https://skrub-data.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Prepping tables for machine learning
  description: |
    Skrub is a Python library to ease preprocessing and feature engineering
    for tabular machine learning. Our long-term goal is to directly connect
    database tables to machine learning estimators.
  dev_url: https://github.com/skrub-data/skrub
  doc_url: https://skrub-data.org/stable/reference/index.html

extra:
  recipe-maintainers:
    - solesnake
